server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # 是否将自己注册到 eureka server,默认为 true。由于当前应用就是 eureka server，故设为 false
    fetch-registry: false # 是否从 eureka server 获取注册信息，默认为 true。因为这是一个单点的 eureka server，不需要同步其它的节点数据，故设为 false
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 设置与 eureka server 交互的地址，查询服务和注册服务都需要依赖这个地址。多个地址使用,分割